tasks:
  - name: "Install requirements"
    init: "pip install -r requirements.txt"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - pkief.material-icon-theme
    - ms-azuretools.vscode-docker
    - vtrois.gitmoji-vscode
